### ISSUE TITLE
Snippet example fails to work, NameError

### ISSUE THREAD

**Issue by ecm-pushbx** [mate-desktop/pluma#416]
#### Expected behaviour

A simple example snippet should work.

#### Actual behaviour

It doesn't work. Details given after the steps to reproduce.

#### Steps to reproduce the behaviour

1. To work around https://github.com/mate-desktop/pluma/issues/415 create the directory /pluma and chown it to the user and the user's group
2. Run "pluma --new-window"
3. Open Tools > Manage Snippets...
4. Click the "Create new snippet" button
5. Enter a name, like "delete first char"
6. Enter a snippet into the Edit pane, like the following:

```
$<
import re
lines = $PLUMA_SELECTED_TEXT.split("\n");
output = "";
for line in lines:
  output += re.sub('^.', r"", line)
return output
>
```

(adapted from an example in https://superuser.com/questions/99512/shortcut-to-remove-first-character-of-multiple-lines-in-gedit )

7. Enter a Shortcut key like Shift+Alt+S
8. Close Snippets Manager
9. Enter text in the main Pluma edit pane, like:

```
111
222
333

```

10. Select all text
11. Press shortcut, eg Shift+Alt+S

This results in the selected text being unchanged, but displays the following to the terminal from which pluma was started:

```
Traceback (most recent call last):
  File "/usr/local/lib/pluma/plugins/snippets/Library.py", line 669, in accelerator_activated
    ret = cb(group, obj, keyval, mod)
  File "/usr/local/lib/pluma/plugins/snippets/__init__.py", line 90, in accelerator_activated
    if _self.helper:
NameError: global name '_self' is not defined
```

I also tried changing PLUMA_SELECTED_TEXT back to GEDIT_SELECTED_TEXT but the result is exactly the same.

#### MATE general version

1.20.0-2

#### Package version

1.20.4-1

#### Linux Distribution

Debian buster

**Comment by ecm-pushbx** [comment]
Same result with the snippet given in https://stackoverflow.com/questions/16828600/how-to-comment-out-multiple-lines-in-pluma-gedit-fork

```
$<
lines = $PLUMA_SELECTED_TEXT.split("\n");
output = "";
for line in lines:
    output += "#" + line + "\n";

return output
>
```

**Comment by ecm-pushbx** [comment]
I checked again with Pluma 1.24.0 from Debian bullseye. This time snippets work. I had to adjust my example snippet to make it accurate in regards to linebreaks but there is no error on Pluma's part any longer. Here's the adjusted example:

```
$<
import re
last_is_newline = False
if $PLUMA_SELECTED_TEXT[-1:] == "\n":
  last_is_newline = True
lines = $PLUMA_SELECTED_TEXT.split("\n");
output = "";
if last_is_newline is True:
  lines = lines[:-1]
for line in lines:
  output += re.sub('^.', r"", line) + "\n"
if last_is_newline is False:
  output = output[:-1]
return output
>
```
